---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  # - ansible # Installed via Pip
  - podman
  - podman-compose
  - git
  - github/gh/gh
  - sqlite
  - qemu
  - zsh-history-substring-search
  - kubernetes-cli
  - kubernetes-helm
  - zsh
  - openshift-cli
  - odo-dev
  - vim
  - unzip

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - mimestream
  - utm 
  - slack
  - balenaetcher
  - browserosaurus
  - discord
  - google-drive
  - grammarly-desktop
  - little-snitch
  - podman-desktop
  - signal
  - switchresx
  - fantastical
  - whatsapp
  state: present
  update_homebrew: yes
